name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.5'

    - name: Install dependencies
      run: |
        go version
        go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

    - name: Build
      run: go build .

    - name: Test With Coverage
      run: go test -gcflags=-l -v ./...

    - name: Run Vet & Lint
      run: |
        go vet ./...
        golangci-lint run


