name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.18.3'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...



